### ISSUE TITLE
Trouble with Nitrous

### ISSUE THREAD

**Issue by maltg** [learn-co-curriculum/ttt-2-board-rb#12]
Hello, I cannot get into Nitrous as of yesterday.  I logged out and logged back in, refreshed my browser, refreshed Nitrous, to no avail.

Can someone help with this?

Thanks,

**Comment by AnnJohn** [comment]
hi @maltg apologies for the delay and sorry for the issue. Since this is a technical problem, can you use the Ask a Question tool instead and if you can, file a bug report? We use this space for issue specifically related to the content in the lessons. Thanks!
