### ISSUE TITLE
Files not downloading to .atom folder or showing in file tree (ttt-2-board-rb-q-000)

### ISSUE THREAD

**Issue by dkennell** [learn-co-curriculum/ttt-2-board-rb#13]
I'm using Atom in the Learn IDE on Windows 10. I'm a very new student, only a few lessons in.
1. Read the 'Tic Tac Toe Board' lesson at learn.co
   (https://learn.co/tracks/intro-to-ruby-development/ruby-basics/variables/tic-tac-toe-board)
2. Open IDE (up to date, as far as I know, downloaded about a week ago)
3. Type `learn open` into the command line.

_Expected behavior: Current lesson is forked, bundled and opened. The .atom\ folder receives the lesson for the files, and the filetree is updated. The user's working directory is changed to the lesson folder._

*Actual Behavior: Current lesson(lab) is not downloaded into the labs folder. The filetree is not updated. However, the user's working directory is changed, and `pwd` returns a location that seemingly does not exist.

I'm new to writing bug reports, but I hope this is usable. Thanks!

![2016-04-26](https://cloud.githubusercontent.com/assets/15965729/14803347/38a846f0-0b8b-11e6-947b-d9533c9f92b3.png)

**Comment by AnnJohn** [comment]
hi @dkennell sorry for the issue. Since this is a technical issue, can you please email  support+ide@learn.co. This way, we'll see the issue and can help you troubleshoot from there. Thanks!
