### ISSUE TITLE
```ttt-2-board-rb-q-000``` folder only contains config file

### ISSUE THREAD

**Issue by dkennell** [learn-co-curriculum/ttt-2-board-rb#14]
When I open this lab in the Atom IDE, the `ttt-2-board-rb-q-000` folder only contains the `.bundle` folder, which in return only contains the `.config` file.

`pwd` actually shows the correct files as being in the directory, but they do not exist in the actual .atom directory on my computer

The issue exists both when the lab is opened from the lab web page, and from the IDE, using `learn open`.
## The bug makes the lab impossible to begin. :(

![2016-05-06 1](https://cloud.githubusercontent.com/assets/15965729/15060905/c7fa6990-1361-11e6-83cf-dd1c6a87cdbe.png)
![2016-05-06 2](https://cloud.githubusercontent.com/assets/15965729/15060906/c7fc8fa4-1361-11e6-842c-681243593bf8.png)
![2016-05-06 3](https://cloud.githubusercontent.com/assets/15965729/15060907/c7fe67ca-1361-11e6-9d93-e0c4ba7f2cb1.png)
![2016-05-06](https://cloud.githubusercontent.com/assets/15965729/15060908/c7feb338-1361-11e6-9a2b-25ab5583ed86.png)

**Comment by AnnJohn** [comment]
hi @dkennell sorry for the issue that you're having this with this. We use this space for issues specifically related to curriculum content. 

Can you use the Ask a Question tool and file a bug report. If you hover over your profile pic in Learn, you'll see an option to file a bug report. 

Thanks!
