### ISSUE TITLE
Cannot Open Lab - Bad Link

### ISSUE THREAD

**Issue by hersrud** [learn-co-curriculum/ttt-2-board-rb#15]
The redirect link for the open button is not correct for the tttt-2-board-rb lab.

**Comment by AnnJohn** [comment]
hi @hersrud this is a technical issue so could you file a bug report instead? If you hover over your profile pic in Learn, you'll see an option to Report a Bug. We use this space specifically for issues related to curriculum content. 

Also you can email support+ide@learn.co for help as well. Thanks!
