### ISSUE TITLE
problem with 'learn' command

### ISSUE THREAD

**Issue by jwhitely333** [learn-co-curriculum/ttt-2-board-rb#16]
When testing solution to the problem with 'learn' command, nothing happens the terminal cursor returns to a new terminal line. When testing the solution to the problem with 'rspec' command, the solution passes with 0 failures.

**Comment by AnnJohn** [comment]
hi @jwhitely333 thanks for raising this. Since this is an issue with the Learn product, could you file a bug report? If you click on your profile pic in Learn, you'll see a dropdown menu with an option in there to 'Report a Bug.' Thanks!
