### ISSUE TITLE
I've submitted this lab, but it doesn't show as submitted on learn.co:

### ISSUE THREAD

**Issue by 11Kilobytes** [learn-co-curriculum/ttt-2-board-rb#17]

**Comment by 11Kilobytes** [comment]
See here for evidence: https://github.com/learn-co-curriculum/ttt-2-board-rb/issues/17

**Comment by cjbrock** [comment]
Hi @11Kilobytes. If you're still having issues with this lab, please contact our Technical Coaches using the Ask A Question button, and they can work with you to help you figure it out. Thank you! --Corinna
