### ISSUE TITLE
Learn Submit

### ISSUE THREAD

**Issue by Th3Schrute** [learn-co-curriculum/ttt-2-board-rb#19]
It will not let me learn submit this lesson so I can move on. Any suggestions on why and how to fix it. I have done all the basics relaunch, restart, login out, cookies

lib/board.rb                                               
  defines a local variable `board`                         
  `board` is set to an array                               
  `board` is an array with 9 elements                      
  `board` is an array with 9 strings with an empty space va
lue, " "                                                   
                                                           
Finished in 0.00669 seconds (files took 0.21962 seconds to 
load)                                                      
4 examples, 0 failures       

// ♥ learn submit                                          
Adding changes...                                          
Committing changes...                                      
It looks like you have no changes to commit. Will still try
 updating your submission...                               
Pushing changes to GitHub...                               
Submitting lesson...                                       
Done.                                                      
[18:35:01] (master) ttt-2-board-rb-cb-gh-000

**Comment by cjbrock** [comment]
Hi @mccauley04! If you're still having issues with this lab, please contact our Technical Coaches using the Ask A Question button, and they can work with you to help you figure it out. Thank you! --Corinna
