### ISSUE TITLE
note seems out of place/not well enough explained

### ISSUE THREAD

**Issue by loganhasson** [learn-co-curriculum/ttt-2-board-rb#2]
This:

```
Note: You should not create a multi-dimensional or nested array. The array should be flat and have only string values.

Remember: Represent a position in the board array as a string with a space in it: " "
```

2 things: 1) it feels like this should come after the instructions and 2) why mention multi-dimensional arrays at all? since they haven't been explained yet, this is kind of confusing. (if anything, there should at least be an explanation of what that means.)

**Comment by PeterBell** [comment]
Hey @loganhasson I'm a little conflicted. I'm sure the underlying concern is that some of the students will create a 2-d array of `[ [" ", " ", " "], [" ", " ", " "], [" ", " ", " "] ]` which I must admit was my first thought (this may be most applicable to people who learned some coding elsewhere). At the same time talking about multi-dimensional arrays is raising some terminology that is new and at this point could be confusing. 

I see the shot @bhollan took at this - I'm going to take a slightly different approach and get some :eyes: on it shortly.

**Comment by PeterBell** [comment]
Resolved
