### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by hopegiometti** [learn-co-curriculum/ttt-2-board-rb#29]
Looking for lesson...
Hmm...Cannot find lesson with repo: ttt-2-board-rb-ruby-intro-000. Please check your input and try again.

This what I get every time I try to open the lab. Have tried a bunch of things to fix it and none of them working. Asked a question and it seems like a lot of other people are having this same problem rn.

**Comment by rrcobb** [comment]
Sorry that this was happening! 

Github issues are looked at by our curriculum team, so if there's a technical issue with learn, the engineering team won't see it if you report it here.

My impression is that the issue has been addressed by the engineering team, but if it hasn't (or if it happens again), let us know and we'll try to address it quickly.
