### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by parora86** [learn-co-curriculum/ttt-2-board-rb#6]
We are not able to scroll the table of contents, therefore, the topics that are towards the bottom cannot be seen. For instance, in Book Intro to Ruby Development, I want to see the sub-topics for Iteration under Chapter Ruby Basics. However, I am only able to see one sub-topic because the list isn't scrollable.

**Comment by AnnJohn** [comment]
Hi @parora86 you should be able to see everything in the menu. It's a collapsible menu so if you click on a unit, you should see the names of the lessons within that unit.
