### ISSUE TITLE
Only middle green light shows

### ISSUE THREAD

**Issue by tal32123** [learn-co-curriculum/ttt-2-board-rb#7]
Learn passed, learn submit worked, yet only green light went on for "local test passed"? Please help/fix this!

**Comment by AnnJohn** [comment]
Hi @tal32123 sorry for this issue. This looks like it's a bug so if you could file a bug report, that would be great. If you hover over your profile pic in Learn, you'll see an option to Report a Bug. 

But also for immediate help to resolve this question, you can use the Ask a Question tool in Learn. Thanks!
